package net.mitask.emcgenesis.api.def;

import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.mitask.emcgenesis.util.ItemUtil;

public class VanillaEMCDef implements EMCDef {
    @Override
    public void addAll() {
        add(Block.STONE, 1);
        add(Block.COBBLESTONE, 1);
        add(Block.GRASS, 1);
        add(Block.DIRT, 1);
        ItemUtil.getItemsOfTag("minecraft:planks").forEach((item) -> add(item, 8));
        ItemUtil.getItemsOfTag("minecraft:saplings").forEach((item) -> add(item, 32));
        add(Block.SAND, 1);
        add(Block.GRAVEL, 4);
        ItemUtil.getItemsOfTag("minecraft:logs").forEach((item) -> add(item, 32));
        ItemUtil.getBlocksOfTag("minecraft:leaves").forEach((block) -> add(block, 1));
        add(Block.GLASS, 1);
        add(Block.LAPIS_BLOCK, 7776);
        add(Block.DISPENSER, 119);
        add(Block.SANDSTONE, 4);
        add(Block.NOTE_BLOCK, 128);
        add(Block.POWERED_RAIL, 2048);
        add(Block.DETECTOR_RAIL, 256);
        add(Block.STICKY_PISTON, 372);
        add(Block.COBWEB, 12);
        add(Block.GRASS, 1);
        add(Block.DEAD_BUSH, 1);
        add(Block.PISTON, 348);
        ItemUtil.getBlocksOfTag("minecraft:wool").forEach((block) -> add(block, 48));
        add(Block.DANDELION, 16);
        add(Block.ROSE, 16);
        add(Block.RED_MUSHROOM, 32);
        add(Block.BROWN_MUSHROOM, 32);
        add(Block.GOLD_BLOCK, 18432);
        add(Block.IRON_BLOCK, 2304);
        addWithMetadata(Block.SLAB, 0, 1);
        addWithMetadata(Block.SLAB, 1, 4);
        addWithMetadata(Block.SLAB, 2, 8);
        addWithMetadata(Block.SLAB, 3, 1);
        add(Block.BRICKS, 64);
        add(Block.TNT, 964);
        add(Block.BOOKSHELF, 336);
        add(Block.OBSIDIAN, 64);
        add(Block.TORCH, 9);
        add(Block.WOODEN_STAIRS, 12);
        add(Block.CHEST, 64);
        add(Block.DIAMOND_BLOCK, 73728);
        add(Block.CRAFTING_TABLE, 32);
        add(Block.FURNACE, 8);
        add(Block.LADDER, 14);
        add(Block.RAIL, 96);
        add(Block.COBBLESTONE_STAIRS, 1);
        add(Block.LEVER, 5);
        add(Block.WOODEN_PRESSURE_PLATE, 2);
        add(Block.STONE_PRESSURE_PLATE, 16);
        add(Block.REDSTONE_TORCH, 68);
        add(Block.BUTTON, 2);
        add(Block.ICE, 1);
        add(Block.SNOW, 1);
        add(Block.CACTUS, 8);
        add(Block.CLAY, 64);
        add(Block.JUKEBOX, 8256);
        add(Block.FENCE, 12);
        add(Block.PUMPKIN, 144);
        add(Block.NETHERRACK, 1);
        add(Block.SOUL_SAND, 49);
        add(Block.GLOWSTONE, 1536);
        add(Block.PUMPKIN, 144);
        add(Block.TRAPDOOR, 24);
        add(Block.FENCE, 96);
        add(Block.LIT_REDSTONE_TORCH, 1792);
//        addWithMetadata(EEBlock, 0, 82953);
//        addWithMetadata(EEBlock, 1, 232969);
//        addWithMetadata(EEBlock, 2, 710665);
//        addWithMetadata(EEBlock, 3, 1114120);
//        addWithMetadata(EEBlock, 4, 2514952);
//        addWithMetadata(EEBlock, 5, 74177);
//        addWithMetadata(EEBlock, 6, 213889);
//        addWithMetadata(EEBlock, 7, 681281);
//        addWithMetadata(EEBlock, 8, 139264);
//        addWithMetadata(EEBlock, 9, 466944);
//        addWithMetadata(EEBlock, 10, 1506);
//        addWithMetadata(EEBlock, 11, 4849);
//        add(Block.EEPEDESTAL, 2564096);
//        addWithMetadata(EEChest, 0, 8987);
//        addWithMetadata(EEChest, 1, 42011);
//        add(Block.EETORCH, 12932);
//        add(EEDevice, 260);
        add(Item.RECORD_CAT, 2048);
        add(Item.RECORD_THIRTEEN, 2048);
        add(Item.IRON_SHOVEL, 264);
        add(Item.IRON_PICKAXE, 776);
        add(Item.IRON_AXE, 776);
        add(Item.FLINT_AND_STEEL, 260);
        add(Item.APPLE, 128);
        add(Item.BOW, 48);
        add(Item.ARROW, 14);
        addWithMetadata(Item.COAL, 0, 128);
        addWithMetadata(Item.COAL, 1, 32);
        add(Item.DIAMOND, 8192);
        add(Item.IRON_INGOT, 256);
        add(Item.GOLD_INGOT, 2048);
        add(Item.IRON_SWORD, 516);
        add(Item.WOODEN_SWORD, 20);
        add(Item.WOODEN_SHOVEL, 16);
        add(Item.WOODEN_PICKAXE, 32);
        add(Item.WOODEN_AXE, 32);
        add(Item.STONE_SWORD, 6);
        add(Item.STONE_SHOVEL, 9);
        add(Item.STONE_PICKAXE, 11);
        add(Item.STONE_AXE, 11);
        add(Item.DIAMOND_SWORD, 16388);
        add(Item.DIAMOND_SHOVEL, 8200);
        add(Item.DIAMOND_PICKAXE, 24584);
        add(Item.DIAMOND_AXE, 24584);
        add(Item.STICK, 4);
        add(Item.BOWL, 6);
        add(Item.GOLDEN_SWORD, 4100);
        add(Item.GOLDEN_SHOVEL, 2056);
        add(Item.GOLDEN_PICKAXE, 6152);
        add(Item.GOLDEN_AXE, 6152);
        add(Item.STRING, 12);
        add(Item.FEATHER, 48);
        add(Item.WOODEN_HOE, 24);
        add(Item.STONE_HOE, 10);
        add(Item.IRON_HOE, 520);
        add(Item.DIAMOND_HOE, 16392);
        add(Item.GOLDEN_HOE, 4104);
        add(Item.SEEDS, 16);
        add(Item.WHEAT, 24);
        add(Item.BREAD, 72);
        add(Item.LEATHER_HELMET, 320);
        add(Item.LEATHER_CHESTPLATE, 512);
        add(Item.LEATHER_LEGGINGS, 448);
        add(Item.LEATHER_BOOTS, 256);
        add(Item.IRON_HELMET, 1280);
        add(Item.IRON_CHESTPLATE, 2048);
        add(Item.IRON_LEGGINGS, 1792);
        add(Item.IRON_BOOTS, 1024);
        add(Item.DIAMOND_HELMET, 40960);
        add(Item.DIAMOND_CHESTPLATE, 65536);
        add(Item.DIAMOND_LEGGINGS, 57344);
        add(Item.DIAMOND_BOOTS, 32768);
        add(Item.GOLDEN_HELMET, 10240);
        add(Item.GOLDEN_CHESTPLATE, 16384);
        add(Item.GOLDEN_LEGGINGS, 14336);
        add(Item.GOLDEN_BOOTS, 8192);
        add(Item.FLINT, 4);
        add(Item.RAW_PORKCHOP, 64);
        add(Item.COOKED_PORKCHOP, 64);
        add(Item.PAINTING, 80);
        add(Item.GOLDEN_APPLE, 1944);
        add(Item.SIGN, 52);
        add(Item.WOODEN_DOOR, 48);
        add(Item.BUCKET, 768);
        add(Item.WATER_BUCKET, 769);
        add(Item.LAVA_BUCKET, 832);
        add(Item.MINECART, 1280);
        add(Item.SADDLE, 192);
        add(Item.IRON_DOOR, 1536);
        add(Item.REDSTONE, 64);
        add(Item.BOAT, 40);
        add(Item.LEATHER, 64);
        add(Item.MILK_BUCKET, 849);
        add(Item.BRICK, 16);
        add(Item.CLAY, 16);
        add(Item.SUGAR_CANE, 32);
        add(Item.PAPER, 32);
        add(Item.BOOK, 96);
        add(Item.SLIMEBALL, 24);
        add(Item.CHEST_MINECART, 1344);
        add(Item.FURNACE_MINECART, 1288);
        add(Item.EGG, 32);
        add(Item.COMPASS, 1088);
        add(Item.FISHING_ROD, 12);
        add(Item.CLOCK, 8256);
        add(Item.GLOWSTONE_DUST, 384);
        add(Item.RAW_FISH, 64);
        add(Item.COOKED_FISH, 64);
        addWithMetadata(Item.DYE, 0, 8);
        addWithMetadata(Item.DYE, 1, 8);
        addWithMetadata(Item.DYE, 2, 8);
        addWithMetadata(Item.DYE, 3, 128);
        addWithMetadata(Item.DYE, 4, 864);
        addWithMetadata(Item.DYE, 5, 8);
        addWithMetadata(Item.DYE, 6, 8);
        addWithMetadata(Item.DYE, 7, 8);
        addWithMetadata(Item.DYE, 8, 8);
        addWithMetadata(Item.DYE, 9, 8);
        addWithMetadata(Item.DYE, 10, 8);
        addWithMetadata(Item.DYE, 11, 8);
        addWithMetadata(Item.DYE, 12, 8);
        addWithMetadata(Item.DYE, 13, 8);
        addWithMetadata(Item.DYE, 14, 8);
        addWithMetadata(Item.DYE, 15, 48);
        add(Item.BONE, 144);
        add(Item.SUGAR, 32);
        add(Item.CAKE, 411);
        add(Item.BED, 168);
        add(Item.REPEATER, 203);
        add(Item.COOKIE, 22);
        add(Item.MAP, 1344);
        add(Item.SHEARS, 512);
//        add(Item.ALCHEMICALCOAL, 512);
//        add(Item.MOBIUSFUEL, 2048);
//        add(Item.DARKMATTER, 139264);
//        addWithMetadata(Item.COVALENCEDUST, 0, 1);
//        addWithMetadata(Item.COVALENCEDUST, 1, 8);
//        addWithMetadata(Item.COVALENCEDUST, 2, 208);
//        add(Item.KLEINSTAR1, 24576);
//        add(Item.KLEINSTAR2, 98304);
//        add(Item.KLEINSTAR3, 393216);
//        add(Item.KLEINSTAR4, 1572864);
//        add(Item.KLEINSTAR5, 6291456);
//        add(Item.REDMATTER, 466944);
//        add(Item.AETERNALISFUEL, 8192);
//        add(Item.KLEINSTAR6, 25165824);
    }
}
